language: ruby
rvm:
  - '2.1'
  - '2.2'
  - 'rbx-2'

gemfile:
  - Gemfile

matrix:

notifications:
  email: false

addons:
  code_climate:
    repo_token: 138fb1975b1869c4bb92f1bcc1c6c5f13668fb47e162e8e04674756185a2b92a
