authors = []
description = ""
executables = []
files = ["from_archive.lock.toml", "spec/tmp/test_package_config/input/2a8aa2f5-460f-432f-b9dd-aaaaba23f865-0", "spec/tmp/test_package_config/input/2a4db58a-bbd8-45e3-a884-41f4cfe57fc2-1", "spec/tmp/test_package_config/input/2a68313c-3c95-4a10-8354-514b3573b2f4-2", "spec/tmp/test_package_config/input/04741120-adf7-4102-9de7-39d335d1525b-3", "spec/tmp/test_package_config/input/855e91fe-fa3a-4e4d-9d6a-235cc79dc0aa-4"]
homepage = ""
name = "from_archive"
short_description = ""
tags = []
version = "1.0.0"
[target]
architecture = "any"
platform = "any"
