authors = []
description = ""
executables = []
files = ["from_archive.lock.toml", "spec/tmp/test_package_config/input/d54dd3fc-1c88-4e46-b245-03b65d20e02d-0", "spec/tmp/test_package_config/input/29e8db61-f725-47bc-a226-74c84622ca6d-1", "spec/tmp/test_package_config/input/0fd1d6dc-7c64-42be-b609-89d383e6a86d-2", "spec/tmp/test_package_config/input/00520725-6d5d-42fe-8d93-a37ac9e25e84-3", "spec/tmp/test_package_config/input/2c77e4f3-8934-442b-a63a-fdbe130d6b9c-4"]
homepage = ""
name = "from_archive"
short_description = ""
tags = []
version = "1.0.0"
[target]
architecture = "any"
platform = "any"
