authors = []
description = ""
executables = []
files = ["from_archive.lock.toml", "spec/tmp/test_package_config/input/0566197f-c5b2-45fd-b26d-fa90f880ae92-0", "spec/tmp/test_package_config/input/25e24f28-3dd7-45b4-85e8-c01b31289494-1", "spec/tmp/test_package_config/input/63e56a18-95c0-4d5d-8ce7-f2079bd2c649-2", "spec/tmp/test_package_config/input/92023f9c-e522-4dee-8da9-b5051621cc73-3", "spec/tmp/test_package_config/input/4f6653bb-0d5a-47a6-bbfd-666fe760ece9-4"]
homepage = ""
name = "from_archive"
short_description = ""
tags = []
version = "1.0.0"
[target]
architecture = "any"
platform = "any"
