authors = []
description = ""
executables = []
files = ["from_archive.lock.toml", "spec/tmp/test_package_config/input/57ff7248-6565-422f-8fe1-879db508d631-0", "spec/tmp/test_package_config/input/2ca9df9c-c780-45dc-9de7-5042341237ac-1", "spec/tmp/test_package_config/input/013a3a7e-c340-4b09-bc58-4fbd17f311b5-2", "spec/tmp/test_package_config/input/a2a84565-c622-4b17-8727-490373f38ce8-3", "spec/tmp/test_package_config/input/1322d957-6a67-4146-80c2-10a68cd6703a-4"]
homepage = ""
name = "from_archive"
short_description = ""
tags = []
version = "1.0.0"
[target]
architecture = "any"
platform = "any"
