authors = []
description = ""
executables = []
files = ["from_archive.lock.toml", "spec/tmp/test_package_config/input/e38fdacd-a47f-45ff-bb34-ab7f2e362d5a-0", "spec/tmp/test_package_config/input/c9b5fceb-5d20-4ac2-aa0f-81838c338da8-1", "spec/tmp/test_package_config/input/d48e3911-af0a-4b1a-8e1c-5a58c4b8aa2b-2", "spec/tmp/test_package_config/input/6f139f7c-49a1-4aef-b583-cea6ed041d3b-3", "spec/tmp/test_package_config/input/cec999a1-8722-421e-872f-9ed11312b1e0-4"]
homepage = ""
name = "from_archive"
short_description = ""
tags = []
version = "1.0.0"
[target]
architecture = "any"
platform = "any"
