authors = []
description = ""
executables = []
files = ["from_archive.lock.toml", "spec/tmp/test_package_config/input/c3c3c221-b2d9-477a-a4e8-d9f8198c6ed4-0", "spec/tmp/test_package_config/input/27787af3-840d-4577-9c7a-1cfc55935140-1", "spec/tmp/test_package_config/input/4a949e96-fd9c-4182-a7ad-9375d1e578e0-2", "spec/tmp/test_package_config/input/5a99d123-5d8f-4133-9416-42a7ef5749b1-3", "spec/tmp/test_package_config/input/5c0fd341-c65c-4955-9d47-659fe9293e3d-4"]
homepage = ""
name = "from_archive"
short_description = ""
tags = []
version = "1.0.0"
[target]
architecture = "any"
platform = "any"
