authors = []
description = ""
executables = []
files = ["from_archive.lock.toml", "spec/tmp/test_package_config/input/0cfecd6d-ab86-42e0-98a5-93519cf20cd8-0", "spec/tmp/test_package_config/input/ecd3f549-f3a9-454a-989c-7d616ad3fd6f-1", "spec/tmp/test_package_config/input/b320f690-d885-4b9b-bb3a-314d3d4ef84d-2", "spec/tmp/test_package_config/input/fb8a7538-1f58-4129-8d83-da2d4ff4ab08-3", "spec/tmp/test_package_config/input/bfdb559d-b3ff-4864-9df1-fa2bd5f8bc48-4"]
homepage = ""
name = "from_archive"
short_description = ""
tags = []
version = "1.0.0"
[target]
architecture = "any"
platform = "any"
