# Name of the package, must contain only letters, digits and _
name = '[Package name]'

# Version of the package, should follow the format major.minor.patch[.other]
version = '[Package Version]'

homepage = '[http://youhomepage.com]'

# List of the authors
authors = ['Your Name <you@example.com>']

# List of the tags
tags = ['Some', 'Tag']

#Short description
summary = '[Short Description]'

# Detailed description of the package(Can be a filename that will be loaded)
description = '[Description]'

# List of files to be added to the package(List of the files to include in the package). 
# Each entry can be a folder, filename, path or a wildcard.
# e.g.
#   src/            => Will include the entire src folder
#   Readme.md       => Will include the Readme.md file
#   bin/myexe       => Will include the bin/myexe file
#   src/**/*.rb     => Will include all the rb files in the src directory
files = ['**/*.*']

# List of files to exclude that are already matched in the files property.(Same format as files)
files_excluded = ['devonly.txt']

# List of executables(Relative to the root of the package) The file will be linked in the WOW bin directory which should be visible by the system path.
executables = ['[Executables]']

# List of application to install with the package. An application is a GUI program.
application = ['[Apllication]']

# Package dependencies
# The version can be in the following format
# 'x.y.z'    => Require version x.y.z
# '= x.y.z'  => Require version x.y.z
# '>= x.y.z' => Require any version more than x.y.z
# '~> x.y.z' => Require any version more thatn x.y.z but less than x.(y+1).0
# You can have multiple conditions speparated with a comma:
# '~> 1.0, >= 1.0.3' => Packge must be between 1.0.3 and 2.0
[dependencies]
# mydependency  = '[Version Pattern]'


# Platform specific config
# Here you can repeat any of the specified config above and it will merge but only for the platform specified
# For example if you had  files = ['src/'] in the main config and add files = ['windows/'] under the [platform.windows] both src and windows will be deployed on install.
[platform.unix]
[platform.linux]
[platform.osx]
[platform.windows]

